cuts:
  MatchedGenMinDR: 1
  NeutronCut: 0.0
  TauPhotonPCut: 0.0
  TauPionPCut: 0.0
  dRMax: 0.4
  generalPCut: 0.0
  tauCut: 0
general:
  decay:
  - -777
  matchedCM: 'True'
  outfile: effis
  sample: ILD
  test: true
output:
  outputfile:
  - effisdecayAll_0.4_tph0.0_tpi0.0_n0.0_g0.0.root
  outputlabels: null
  outputpath: ParticleEval_Results/TauReco/ILD_effis0.4_tph0.0_tpi0.0_n0.0_g0.0/
