global:
  luminosity: 6972
datasets:
- path: Results/RhoAnalysis/FULL_sample_tau_trained0.4_tph0.35_tpi0_n3_g0.0/Histos_dRgt3.06_5.0_MesonPgt0.0_lt45.57_LeptonPgt0.0_lt41.16_tau_traineddecay2_0.4_tph0.35_tpi0_n3_g0.0.root
  label: Signal
  color: ROOT.kRed
  linestyle: 1
  markerstyle: 20
  markersize: 1.0
  linewidth: 3
  xsec: 1476.58
  n_events: 10296000
- path: Results/RhoAnalysis/FULL_sample_tau_trained0.4_tph0.35_tpi0_n3_g0.0/Histos_dRgt3.06_5.0_MesonPgt0.0_lt45.57_LeptonPgt0.0_lt41.16_tau_traineddecay2_0.4_tph0.35_tpi0_n3_g0.0.root
  label: Template P1
  color: ROOT.kGreen+4
  linestyle: 10
  markerstyle: 20
  markersize: 1.0
  linewidth: 3
  xsec: 1476.58
  n_events: 20592000
- path: Results/RhoAnalysis/FULL_sample_tau_trained0.4_tph0.35_tpi0_n3_g0.0/Histos_dRgt3.06_5.0_MesonPgt0.0_lt45.57_LeptonPgt0.0_lt41.16_tau_traineddecay2_0.4_tph0.35_tpi0_n3_g0.0.root
  label: Template M1
  color: ROOT.kGreen+4
  linestyle: 7
  markerstyle: 20
  markersize: 1.0
  linewidth: 3
  xsec: 1476.58
  n_events: 20592000
- path: Results/RhoAnalysis/FULL_sample_tau_trained0.4_tph0.35_tpi0_n3_g0.0/Histos_dRgt3.06_5.0_MesonPgt0.0_lt45.57_LeptonPgt0.0_lt41.16_tau_traineddecay2_0.4_tph0.35_tpi0_n3_g0.0.root
  label: Migrations BG
  color: ROOT.kViolet
  linestyle: 1
  markerstyle: 20
  markersize: 1.0
  linewidth: 3
  fill: true
  fillstyle: 1001      # Sólido
  fillalpha: 0.5  
  xsec: 1476.58
  n_events: 10296000
- path: Results/RhoAnalysis/bhabha_sample_FULLtau_trained0.4_tph0.35_tpi0_n3_g0.0/Histos_dRgt3.06_5.0_MesonPgt0.0_lt45.57_LeptonPgt0.0_lt41.16_tau_traineddecay2_0.4_tph0.35_tpi0_n3_g0.0.root
  label: Bhabha BG
  color: ROOT.kBlue-2
  linestyle: 1
  markerstyle: 21
  markersize: 1.0
  linewidth: 3
  fill: true
  fillstyle: 1001      # Sólido
  fillalpha: 0.5   
  xsec: 273500
  n_events: 2396000
- path: Results/RhoAnalysis/Zqq_sampletau_trained0.4_tph0.35_tpi0_n3_g0.0/Histos_dRgt3.06_5.0_MesonPgt0.0_lt45.57_LeptonPgt0.0_lt41.16_tau_traineddecay2_0.4_tph0.35_tpi0_n3_g0.0.root
  label: Zqq BG
  color: ROOT.kOrange+7 
  linestyle: 1
  markerstyle: 21
  markersize: 1.0
  linewidth: 3
  fill: true
  fillstyle: 1001      # Sólido
  fillalpha: 0.5  
  xsec: 30170
  n_events: 1000000
plots:
  signal_vs_BG_pol_templates_optimal:
    rebin: 4
    per_dataset:
      Signal: Omega_SIGNAL
      Template P1: Omega_SIGNAL_P1
      Template M1: Omega_SIGNAL_M1
      Zqq BG: Omega_BGOther
      Bhabha BG: Omega_BGOther
      Migrations BG: Omega_BG
    title: \text{Signal vs Background Omega (}\rho \text{ decay)}
    x: \omega
    y: Events
    sum_histos:
      Pseudodata:
        sources:
        - from: Signal
          histo: Omega_SIGNAL
        - from: Migrations BG
          histo: Omega_BG
        - from: Bhabha BG
          histo: Omega_BGOther
        - from: Zqq BG
          histo: Omega_BGOther
        color: ROOT.kBlack
        linestyle: 1
        linewidth: 3
        markerstyle: 20
        markersize: 0.8
        draw_with_errors: true
        label: \text{Pseudodata, } \rho  \text{  }2\gamma\text{ channel}
    show_entries: absolute
    ignore_entries_for:
    - Template P1
    - Template M1
    - Pseudodata
    legend:
    - 0.55
    - 0.5
    - 0.9
    - 0.85
    legend_txt_size: 0.03
    extra_legend:
    - 7 fb^{-1}\text{  }\sqrt{s}=91GeV
  signal_vs_BG_costheta_templates_optimal:
    rebin: 2
    per_dataset:
      Signal: CosTheta_SIGNAL
      Template P1: CosTheta_SIGNAL_P1
      Template M1: CosTheta_SIGNAL_M1
      Zqq BG: CosTheta_BGOther
      Bhabha BG: CosTheta_BGOther
      Migrations BG: CosTheta_BG
    title: \text{Signal vs Background} \cos\theta \text{(}\rho \text{ decay)}
    x: \cos\theta
    y: Events
    sum_histos:
      Pseudodata:
        sources:
        - from: Signal
          histo: CosTheta_SIGNAL
        - from: Migrations BG
          histo: CosTheta_BG
        - from: Bhabha BG
          histo: CosTheta_BGOther
        - from: Zqq BG
          histo: CosTheta_BGOther
        color: ROOT.kBlack
        linestyle: 1
        linewidth: 3
        markerstyle: 20
        markersize: 0.8
        draw_with_errors: true
        label: \text{Pseudodata, } \rho  \text{  }2\gamma\text{ channel}
    show_entries: absolute
    ignore_entries_for:
    - Template P1
    - Template M1
    legend:
    - 0.65
    - 0.7
    - 0.9
    - 0.9
    legend_txt_size: 0.02
    extra_legend:
    - 7 fb^{-1}\text{  }\sqrt{s}=91GeV
  signal_vs_BG_cospsi_templates_optimal:
    rebin: 2
    per_dataset:
      Signal: CosPsi_SIGNAL
      Template P1: CosPsi_SIGNAL_P1
      Template M1: CosPsi_SIGNAL_M1
      Zqq BG: CosPsi_BGOther
      Bhabha BG: CosPsi_BGOther
      Migrations BG: CosPsi_BG
    title: \text{Signal vs Background} \cos\psi \text{(}\rho \text{ decay)}
    x: \cos\psi
    y: Events
    sum_histos:
      Pseudodata:
        sources:
        - from: Signal
          histo: CosPsi_SIGNAL
        - from: Migrations BG
          histo: CosPsi_BG
        - from: Bhabha BG
          histo: CosPsi_BGOther
        - from: Zqq BG
          histo: CosPsi_BGOther
        color: ROOT.kBlack
        linestyle: 1
        linewidth: 3
        markerstyle: 20
        markersize: 0.8
        draw_with_errors: true
        label: \text{Pseudodata, } \rho  \text{  }2\gamma\text{ channel}
    show_entries: absolute
    ignore_entries_for:
    - Template P1
    - Template M1
    legend:
    - 0.35
    - 0.5
    - 0.9
    - 0.85
    legend_txt_size: 0.04
    extra_legend:
    - 7 fb^{-1}\text{  }\sqrt{s}=91GeV
