# compare.yaml
# global:
  # luminosity: 677 # in pb-1

datasets:
  # - path: Results/RhoAnalysis/PolAnalysis_SM_tau_trained0.4_tph0.35_tpi0_n3_g0.0/Histos_tau_traineddecay2_0.4_tph0.35_tpi0_n3_g0.0.root
  - path: Results/RhoAnalysis/PolAnalysis_GEN_SM_ALL_tau_trained0.4_tph0.35_tpi0_n3_g0.0/HistosMDecs_2_-13_tau_traineddecayAll_0.4_tph0.35_tpi0_n3_g0.0.root  
    
    label: SM (weight P1)
    color: ROOT.kRed          # kRed
    linestyle: 1
    markerstyle: 20
    markersize: 1.
    linewidth: 3
    # xsec: 273500 # pb
    # n_events: 1000000

  - path: Results/RhoAnalysis/PolAnalysis_GEN_P1_ALL_tau_trained0.4_tph0.35_tpi0_n3_g0.0/HistosMDecs_2_-13_tau_traineddecayAll_0.4_tph0.35_tpi0_n3_g0.0.root
    label: P1
    color: ROOT.kBlue+2         # kBlue
    linestyle: 2
    markerstyle: 21
    markersize: 1.
    linewidth: 3
    # xsec: 273500 # pb
    # n_events: 2000000

  - path: Results/RhoAnalysis/PolAnalysis_GEN_M1_ALL_tau_trained0.4_tph0.35_tpi0_n3_g0.0/HistosMDecs_2_-13_tau_traineddecayAll_0.4_tph0.35_tpi0_n3_g0.0.root
    label: M1
    color: ROOT.kBlue          # kBlue
    linestyle: 2
    markerstyle: 21
    markersize: 1.
    linewidth: 3
    # xsec: 273500 # pb
    # n_events: 2000000

plots: 
  GenTauP_omega_neg_rho_P1:
    per_dataset:
      SM (weight P1): TauP_omega_neg_dec0_SIGNAL_SIGNAL_M1
      P1: TauP_omega_neg_dec0_SIGNAL_SIGNAL
    title: \text{Gen Tau P for }\omega < 0 \text{ } \rho \text{ decay} 
    x: P_{\tau} \text{ [GeV]}
    y: A.U. 
    normalize: "max"
    legend: [0.35, 0.32, 0.5, 0.52]
    rebin: 4
  
  GenTauP_omega_neg_rho_P1_corr:
    per_dataset:
      SM (weight P1): TauP_omega_neg_dec0_SIGNAL_SIGNAL_corr_M1
      P1: TauP_omega_neg_dec0_SIGNAL_SIGNAL
    title: \text{Gen Tau P for }\omega < 0 \text{ } \rho \text{ decay corr with } \mu 
    x: P_{\tau} \text{ [GeV]}
    y: A.U. 
    normalize: "max"
    legend: [0.35, 0.32, 0.5, 0.52]
    rebin: 4

  GenTauTheta_omega_neg_rho_P1:
    per_dataset:
      SM (weight P1): TauTheta_omega_neg_dec0_SIGNAL_SIGNAL_M1
      P1: TauTheta_omega_neg_dec0_SIGNAL_SIGNAL
    title: \text{Gen Tau Theta for }\omega < 0 \text{ } \rho \text{ decay} 
    x: \theta_{\tau} \text{ [rad]}
    y: A.U. 
    normalize: "max"
    legend: [0.35, 0.32, 0.5, 0.52]
    rebin: 4
  
  GenTauTheta_omega_neg_rho_P1_corr:
    per_dataset:
      SM (weight P1): TauTheta_omega_neg_dec0_SIGNAL_SIGNAL_corr_M1
      P1: TauTheta_omega_neg_dec0_SIGNAL_SIGNAL
    title: \text{Gen Tau Theta for }\omega < 0 \text{ } \rho \text{ decay corr with } \mu 
    x: \theta_{\tau} \text{ [rad]}
    y: A.U. 
    normalize: "max"
    legend: [0.35, 0.32, 0.5, 0.52]
    rebin: 4



  GenTauPhi_omega_neg_rho_P1:
    per_dataset:
      SM (weight P1): TauPhi_omega_neg_dec0_SIGNAL_SIGNAL_M1
      P1: TauPhi_omega_neg_dec0_SIGNAL_SIGNAL
    title: \text{Gen Tau Phi for }\omega < 0 \text{ } \rho \text{ decay} 
    x: \phi_{\tau} \text{ [rad]}
    y: A.U. 
    normalize: "max"
    legend: [0.35, 0.32, 0.5, 0.52]
    rebin: 4
  
  GenTauPhi_omega_neg_rho_P1_corr:
    per_dataset:
      SM (weight P1): TauPhi_omega_neg_dec0_SIGNAL_SIGNAL_corr_M1
      P1: TauPhi_omega_neg_dec0_SIGNAL_SIGNAL
    title: \text{Gen Tau Phi for }\omega < 0 \text{ } \rho \text{ decay corr with } \mu 
    x: \phi_{\tau} \text{ [rad]}
    y: A.U. 
    normalize: "max"
    legend: [0.35, 0.32, 0.5, 0.52]
    rebin: 4

  
  GenTauVisP_omega_neg_rho_P1:
    per_dataset:
      SM (weight P1): VisP_omega_neg_dec0_SIGNAL_SIGNAL_M1
      P1: VisP_omega_neg_dec0_SIGNAL_SIGNAL
    title: \text{Gen Tau Vis P for }\omega < 0 \text{ } \rho \text{ decay} 
    x: P_{\tau} \text{ [GeV]}
    y: A.U. 
    normalize: "max"
    legend: [0.35, 0.32, 0.5, 0.52]
    rebin: 4
  
  GenTauVisP_omega_neg_rho_P1_corr:
    per_dataset:
      SM (weight P1): VisP_omega_neg_dec0_SIGNAL_SIGNAL_corr_M1
      P1: VisP_omega_neg_dec0_SIGNAL_SIGNAL
    title: \text{Gen Tau Vis P for }\omega < 0 \text{ } \rho \text{ decay corr with } \mu 
    x: P_{\tau} \text{ [GeV]}
    y: A.U. 
    normalize: "max"
    legend: [0.35, 0.32, 0.5, 0.52]
    rebin: 4
  

  Omega_GEN_SIGNAL_ALL_P1:
    per_dataset:
      SM (weight P1): Omega_dec0_SIGNAL_SIGNAL_M1
      P1: Omega_dec0_SIGNAL_SIGNAL
    title: \omega \text{ distribution for } \rho \text{ decay}
    x: \omega
    y: "Norm Events"
    normalize: "max"
    legend: [0.65, 0.32, 0.9, 0.42]
    rebin: 4
  
  Omega_GEN_SIGNAL_ALL_P1_corr:
    per_dataset:
      SM (weight P1): Omega_dec0_SIGNAL_SIGNAL_corr_M1
      P1: Omega_dec0_SIGNAL_SIGNAL
    title: \omega \text{ distribution for } \rho \text{ decay corr with } \mu
    x: \omega
    y: "Norm Events"
    normalize: "max"
    legend: [0.65, 0.32, 0.9, 0.42]
    rebin: 4