migrations:
  0->-20: [0,-20]
  0->0: [0,0]
  0->10: [0,10]
  10->-20: [10,-20]
  10->10: [10,10]  
  10->0: [10,0]
axis:
  xlabel: "Neutral Hadrons P Cut (GeV/c)"
  title: "Migrations regarding Neutral Hadrons P Cut"
metric: "recall"