migrations:
  0->0: [0,0]
  0->1: [0,1]
  0->2: [0,2]
  1->1: [1,1]
  1->0: [1,0]
  1->2: [1,2]
  2->2: [2,2]
  2->0: [2,0]
  2->1: [2,1]
axis:
  xlabel: "Photon P Cut (GeV(c))"
  title: "Migrations regarding Photons P Cut"
metric: "recall"