variabs_hist:
  - hRecoConstPi0Mass
  - hRecoConstPi0MassFromPhotonMasstr
  - hRecoConstPi0MassFromPhotonDiststr
  - hRecoConstlessPhotonPa1strMass
  - hRecoConstlessPhotonPa1strDist
  - hRecoConstxtraPhotonPrhostrMass
  - hRecoConstxtraPhotonPrhostrDist
  - hRecoConstlessPhotonPrho
  - hRecoConstxtraPhotonPi
plot_together:
  Pi0Mass:
    variabs:
      - hRecoConstPi0Mass
      - hRecoConstPi0MassFromPhotonMasstr
      - hRecoConstPi0MassFromPhotonDiststr
    labels:
      - 2 photons.
      - 3 ph., Mass Str.
      - 3 ph., Dist Str.
    title: "Histogram of Pi0 Mass"
    x: "Pi0 Mass [GeV]"
    y: "Events"
    norm: True

  ThreePhotonsPMass:
    variabs:
      - hRecoConstlessPhotonPa1strMass
      - hRecoConstxtraPhotonPrhostrMass
    labels:
      - 3 Photons Mass (Mass Strategy) - a1
      - 3 Photons Mass (Mass Strategy) - rho
    title: "Histogram of 3 Photons cases P (Mass Strategy)"
    x: "Photon P [GeV]"
    y: "Events"
  
  ThreePhotonsPDist:
    variabs:
      - hRecoConstlessPhotonPa1strDist
      - hRecoConstxtraPhotonPrhostrDist
    labels:
      - 3 Photons Mass - a1
      - 3 Photons Mass - rho
    title: "Histogram of 3 Photons cases P (Dist Strategy)"
    x: "Photon P [GeV]"
    y: "Events"

  OnePhotonP:
    variabs:
      - hRecoConstlessPhotonPrho
      - hRecoConstxtraPhotonPi
    labels:
      - 1 Photon P - rho
      - 1 Photon P - pi
    title: "Histogram of 1 Photon P"
    x: "1 Photon P [GeV]"
    y: "Events"

plot_titles_config_hist:
  hRecoConstPi0Mass:
    title: "Pi0 Mass"
    x: "Pi0 Mass [GeV]"
    y: "Events"
  hRecoConstPi0MassFromPhotonMasstr:
    title: "Pi0 Mass from Photon - Mass strategy"
    x: "Pi0 Mass [GeV]"
    y: "Events"
  hRecoConstPi0MassFromPhotonDiststr:
    title: "Pi0 Mass from Photon - Dist strategy"
    x: "Pi0 Mass [GeV]"
    y: "Events"
  hRecoConstlessPhotonPa1strMass:
    title: "3 Photons Mass (Mass Strategy) - a1"
    x: "Photon P [GeV]"
    y: "Events"
  hRecoConstlessPhotonPa1strDist:
    title: "3 Photons Mass (Dist Strategy) - a1"
    x: "Photon P [GeV]"
    y: "Events"
  hRecoConstxtraPhotonPrhostrMass:
    title: "3 Photons Mass (Mass Strategy) - rho"
    x: "Photon P [GeV]"
    y: "Events"
  hRecoConstxtraPhotonPrhostrDist:
    title: "3 Photons Mass (Dist Strategy) - rho"
    x: "Photon P [GeV]"
    y: "Events"
  hRecoConstlessPhotonPrho:
    title: "1 Photon P - rho"
    x: "Photon P [GeV]"
    y: "Events"
  hRecoConstxtraPhotonPi:
    title: "1 Photon P - pi"
    x: "Photon P [GeV]"
    y: "Events"
variabs_2d:

plot_titles_config_2d:
