+CieRunInGpu3       = True
+CieMediumJob       = True
requirements        = TARGET.Machine == "gaew0120.ciemat.es"

executable          = /nfs/cms/arqolmo/ExamplesFCCFullSim/condor/condorExecutableTabPFN.sh

environment         = "TABPFN_TOKEN=<TU_TOKEN>"

output              = /nfs/cms/arqolmo/ExamplesFCCFullSim/condor/logs/tabpfn.out
log                 = /nfs/cms/arqolmo/ExamplesFCCFullSim/condor/logs/tabpfn.log
error               = /nfs/cms/arqolmo/ExamplesFCCFullSim/condor/logs/tabpfn.err

request_cpus        = 4
request_gpus        = 1

max_retries         = 0

queue
